deployment:
  tasks:
    - export DEPLOYPATH=/home1/de2shrnx/transactions.easi7.in
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH/private
    - /bin/cp -R backend/public/. $DEPLOYPATH/
    - /bin/cp backend/bootstrap.php $DEPLOYPATH/private/bootstrap.php
    - /bin/cp backend/config.example.php $DEPLOYPATH/private/config.example.php
    - /bin/rm -rf $DEPLOYPATH/private/src
    - /bin/mkdir -p $DEPLOYPATH/private/src
    - /bin/cp -R backend/src/. $DEPLOYPATH/private/src/
    - /bin/mkdir -p $DEPLOYPATH/private/sql
    - /bin/cp backend/schema.sql $DEPLOYPATH/private/schema.sql
    - /bin/cp backend/sql/seed_defaults.sql $DEPLOYPATH/private/sql/seed_defaults.sql
    - /bin/cp backend/README.md $DEPLOYPATH/private/README.md
    - if [ ! -f $DEPLOYPATH/private/config.php ]; then /bin/cp $DEPLOYPATH/private/config.example.php $DEPLOYPATH/private/config.php; fi
